In [70]:
import pandas as pd
import glob
import numpy as np

In [71]:
folderpath = "data/us_covid19_vaccine_cases_deaths.csv"
df = pd.read_csv(folderpath)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42706 entries, 0 to 42705
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Province_State               42706 non-null  object
 1   Country_Region               42706 non-null  object
 2   Last_Update                  42687 non-null  object
 3   Lat                          41216 non-null  float64
 4   Long                         41216 non-null  float64
 5   Confirmed                    42706 non-null  int64
 6   Deaths                       42706 non-null  int64
 7   Recovered                    15122 non-null  float64
 8   Active                       15122 non-null  float64
 9   FIPS                         42687 non-null  float64
 10  Incident_Rate                41216 non-null  float64
 11  Total_Test_Results           28973 non-null  float64
 12  People_Hospitalized          5129 non-null   float64
 13  Case_Fatality_Ratio          30119 non-null  float64
 14  UID                          42706 non-null  float64
 15  ISO3                         42706 non-null  object
 16  Testing_Rate                 40789 non-null  float64
 17  Hospitalization_Rate         5129 non-null   float64
 18  date                         42706 non-null  object
 19  People_Tested                11816 non-null  float64
 20  Mortality_Rate               12027 non-null  float64
 21  Combined_Key                 27664 non-null  object
 22  People_Fully_Vaccinated      25635 non-null  float64
 23  People_Partially_Vaccinated  25635 non-null  float64
dtypes: float64(16), int64(2), object(6)
memory usage: 7.8+ MB

In [72]:
df = df.sort_values(by=['Province_State', 'date'])

In [73]:
df.loc[:, 'daily_confirmed'] = np.where(df.Province_State == df.Province_State.shift(1), df.Confirmed.diff(), 0)
df.loc[:, 'daily_deaths'] = np.where(df.Province_State == df.Province_State.shift(1), df.Deaths.diff(), 0)
df.loc[:, 'daily_partially_vaccinated'] = np.where(df.Province_State == df.Province_State.shift(1), df.People_Partially_Vaccinated.diff(), 0)
df.loc[:, 'daily_fully_vaccinated'] = np.where(df.Province_State == df.Province_State.shift(1), df.People_Fully_Vaccinated.diff(), 0)

In [74]:
df['daily_confirmed'] = np.where(df['daily_confirmed'] < 0, 0, df['daily_confirmed'])
df['daily_deaths'] = np.where(df['daily_deaths'] < 0, 0, df['daily_deaths'])
df['daily_partially_vaccinated'] = np.where(df['daily_partially_vaccinated'] < 0, 0, df['daily_partially_vaccinated'])
df['daily_fully_vaccinated'] = np.where(df['daily_fully_vaccinated'] < 0, 0, df['daily_fully_vaccinated'])

In [79]:
df['daily_partially_vaccinated'] = df['daily_partially_vaccinated'].fillna(0)
df['daily_fully_vaccinated'] = df['daily_fully_vaccinated'].fillna(0)

In [80]:
df

,Province_State,Country_Region,Last_Update,Lat,Long,Confirmed,Deaths,Recovered,Active,FIPS,...,date,People_Tested,Mortality_Rate,Combined_Key,People_Fully_Vaccinated,People_Partially_Vaccinated,daily_confirmed,daily_deaths,daily_partially_vaccinated,daily_fully_vaccinated
11716,Alabama,US,2020-04-12 23:18:15,32.3182,-86.9023,3667,93,NaN,NaN,1.0,...,2020-04-12,62029.0,2.536133,NaN,NaN,NaN,0.0,0.0,0.0,0.0
11891,Alabama,US,2020-04-13 23:07:54,32.3182,-86.9023,3870,99,NaN,NaN,1.0,...,2020-04-13,64636.0,2.558140,NaN,NaN,NaN,203.0,6.0,0.0,0.0
12066,Alabama,US,2020-04-14 23:33:31,32.3182,-86.9023,4041,114,NaN,NaN,1.0,...,2020-04-14,67557.0,2.821084,NaN,NaN,NaN,171.0,15.0,0.0,0.0
12241,Alabama,US,2020-04-15 22:56:51,32.3182,-86.9023,4307,118,NaN,NaN,1.0,...,2020-04-15,70823.0,2.739726,NaN,NaN,NaN,266.0,4.0,0.0,0.0
12416,Alabama,US,2020-04-16 23:30:51,32.3182,-86.9023,4465,133,NaN,NaN,1.0,...,2020-04-16,73878.0,2.978723,NaN,NaN,NaN,158.0,15.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12065,Wyoming,US,2022-04-14 04:31:32,42.7560,-107.3025,156258,1801,NaN,NaN,56.0,...,2022-04-13,NaN,NaN,"Wyoming, US",296952.0,42014.0,0.0,0.0,2.0,84.0
12240,Wyoming,US,2022-04-15 04:31:45,42.7560,-107.3025,156258,1801,NaN,NaN,56.0,...,2022-04-14,NaN,NaN,"Wyoming, US",297028.0,42030.0,0.0,0.0,16.0,76.0
12415,Wyoming,US,2022-04-16 04:32:40,42.7560,-107.3025,156258,1801,NaN,NaN,56.0,...,2022-04-15,NaN,NaN,"Wyoming, US",297113.0,42056.0,0.0,0.0,26.0,85.0
12590,Wyoming,US,2022-04-17 04:32:15,42.7560,-107.3025,156258,1801,NaN,NaN,56.0,...,2022-04-16,NaN,NaN,"Wyoming, US",297214.0,42067.0,0.0,0.0,11.0,101.0
12765,Wyoming,US,2022-04-18 04:32:51,42.7560,-107.3025,156258,1801,NaN,NaN,56.0,...,2022-04-17,NaN,NaN,"Wyoming, US",297236.0,42072.0,0.0,0.0,5.0,22.0

In [77]:
df.to_csv('data/us_covid19_vaccine_cases_deaths_daily_count.csv', index=False)