In [5]:
import pandas as pd
import numpy as np
import datetime

In [2]:
folderpath = "data/us_covid19_vaccine_cases_deaths_daily_count.csv"
df = pd.read_csv(folderpath)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42706 entries, 0 to 42705
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Province_State               42706 non-null  object
 1   Country_Region               42706 non-null  object
 2   Last_Update                  42687 non-null  object
 3   Lat                          41216 non-null  float64
 4   Long                         41216 non-null  float64
 5   Confirmed                    42706 non-null  int64
 6   Deaths                       42706 non-null  int64
 7   Recovered                    15122 non-null  float64
 8   Active                       15122 non-null  float64
 9   FIPS                         42687 non-null  float64
 10  Incident_Rate                41216 non-null  float64
 11  Total_Test_Results           28973 non-null  float64
 12  People_Hospitalized          5129 non-null   float64
 13  Case_Fatality_Ratio          30119 non-null  float64
 14  UID                          42706 non-null  float64
 15  ISO3                         42706 non-null  object
 16  Testing_Rate                 40789 non-null  float64
 17  Hospitalization_Rate         5129 non-null   float64
 18  date                         42706 non-null  object
 19  People_Tested                11816 non-null  float64
 20  Mortality_Rate               12027 non-null  float64
 21  Combined_Key                 27664 non-null  object
 22  People_Fully_Vaccinated      25635 non-null  float64
 23  People_Partially_Vaccinated  25635 non-null  float64
 24  daily_confirmed              42706 non-null  float64
 25  daily_deaths                 42706 non-null  float64
 26  daily_partially_vaccinated   42706 non-null  float64
 27  daily_fully_vaccinated       42706 non-null  float64
dtypes: float64(20), int64(2), object(6)
memory usage: 9.1+ MB

In [4]:
df['date'] = pd.to_datetime(df['date']).dt.date
df

,Province_State,Country_Region,Last_Update,Lat,Long,Confirmed,Deaths,Recovered,Active,FIPS,...,date,People_Tested,Mortality_Rate,Combined_Key,People_Fully_Vaccinated,People_Partially_Vaccinated,daily_confirmed,daily_deaths,daily_partially_vaccinated,daily_fully_vaccinated
0,Alabama,US,2020-04-12 23:18:15,32.3182,-86.9023,3667,93,NaN,NaN,1.0,...,2020-04-12,62029.0,2.536133,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1,Alabama,US,2020-04-13 23:07:54,32.3182,-86.9023,3870,99,NaN,NaN,1.0,...,2020-04-13,64636.0,2.558140,NaN,NaN,NaN,203.0,6.0,0.0,0.0
2,Alabama,US,2020-04-14 23:33:31,32.3182,-86.9023,4041,114,NaN,NaN,1.0,...,2020-04-14,67557.0,2.821084,NaN,NaN,NaN,171.0,15.0,0.0,0.0
3,Alabama,US,2020-04-15 22:56:51,32.3182,-86.9023,4307,118,NaN,NaN,1.0,...,2020-04-15,70823.0,2.739726,NaN,NaN,NaN,266.0,4.0,0.0,0.0
4,Alabama,US,2020-04-16 23:30:51,32.3182,-86.9023,4465,133,NaN,NaN,1.0,...,2020-04-16,73878.0,2.978723,NaN,NaN,NaN,158.0,15.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42701,Wyoming,US,2022-04-14 04:31:32,42.7560,-107.3025,156258,1801,NaN,NaN,56.0,...,2022-04-13,NaN,NaN,"Wyoming, US",296952.0,42014.0,0.0,0.0,2.0,84.0
42702,Wyoming,US,2022-04-15 04:31:45,42.7560,-107.3025,156258,1801,NaN,NaN,56.0,...,2022-04-14,NaN,NaN,"Wyoming, US",297028.0,42030.0,0.0,0.0,16.0,76.0
42703,Wyoming,US,2022-04-16 04:32:40,42.7560,-107.3025,156258,1801,NaN,NaN,56.0,...,2022-04-15,NaN,NaN,"Wyoming, US",297113.0,42056.0,0.0,0.0,26.0,85.0
42704,Wyoming,US,2022-04-17 04:32:15,42.7560,-107.3025,156258,1801,NaN,NaN,56.0,...,2022-04-16,NaN,NaN,"Wyoming, US",297214.0,42067.0,0.0,0.0,11.0,101.0
42705,Wyoming,US,2022-04-18 04:32:51,42.7560,-107.3025,156258,1801,NaN,NaN,56.0,...,2022-04-17,NaN,NaN,"Wyoming, US",297236.0,42072.0,0.0,0.0,5.0,22.0

In [11]:
df.loc[:, 'Variant'] = np.where(df['date'] <= datetime.datetime(2020, 9, 30).date(), 'Alpha', np.where((df['date'] > datetime.datetime(2020, 9, 30).date()) & (df['date'] <= datetime.datetime(2021, 7, 31).date()), 'Delta', 'Omicron'))

In [12]:
df

,Province_State,Country_Region,Last_Update,Lat,Long,Confirmed,Deaths,Recovered,Active,FIPS,...,People_Tested,Mortality_Rate,Combined_Key,People_Fully_Vaccinated,People_Partially_Vaccinated,daily_confirmed,daily_deaths,daily_partially_vaccinated,daily_fully_vaccinated,Variant
0,Alabama,US,2020-04-12 23:18:15,32.3182,-86.9023,3667,93,NaN,NaN,1.0,...,62029.0,2.536133,NaN,NaN,NaN,0.0,0.0,0.0,0.0,Alpha
1,Alabama,US,2020-04-13 23:07:54,32.3182,-86.9023,3870,99,NaN,NaN,1.0,...,64636.0,2.558140,NaN,NaN,NaN,203.0,6.0,0.0,0.0,Alpha
2,Alabama,US,2020-04-14 23:33:31,32.3182,-86.9023,4041,114,NaN,NaN,1.0,...,67557.0,2.821084,NaN,NaN,NaN,171.0,15.0,0.0,0.0,Alpha
3,Alabama,US,2020-04-15 22:56:51,32.3182,-86.9023,4307,118,NaN,NaN,1.0,...,70823.0,2.739726,NaN,NaN,NaN,266.0,4.0,0.0,0.0,Alpha
4,Alabama,US,2020-04-16 23:30:51,32.3182,-86.9023,4465,133,NaN,NaN,1.0,...,73878.0,2.978723,NaN,NaN,NaN,158.0,15.0,0.0,0.0,Alpha
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42701,Wyoming,US,2022-04-14 04:31:32,42.7560,-107.3025,156258,1801,NaN,NaN,56.0,...,NaN,NaN,"Wyoming, US",296952.0,42014.0,0.0,0.0,2.0,84.0,Omicron
42702,Wyoming,US,2022-04-15 04:31:45,42.7560,-107.3025,156258,1801,NaN,NaN,56.0,...,NaN,NaN,"Wyoming, US",297028.0,42030.0,0.0,0.0,16.0,76.0,Omicron
42703,Wyoming,US,2022-04-16 04:32:40,42.7560,-107.3025,156258,1801,NaN,NaN,56.0,...,NaN,NaN,"Wyoming, US",297113.0,42056.0,0.0,0.0,26.0,85.0,Omicron
42704,Wyoming,US,2022-04-17 04:32:15,42.7560,-107.3025,156258,1801,NaN,NaN,56.0,...,NaN,NaN,"Wyoming, US",297214.0,42067.0,0.0,0.0,11.0,101.0,Omicron
42705,Wyoming,US,2022-04-18 04:32:51,42.7560,-107.3025,156258,1801,NaN,NaN,56.0,...,NaN,NaN,"Wyoming, US",297236.0,42072.0,0.0,0.0,5.0,22.0,Omicron

In [13]:
df.to_csv('data/us_covid19_vaccine_cases_deaths_daily_count_variant.csv', index=False)